org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
enabled_platforms=fabric,neoforge

archives_base_name=visualoverhaul-legacy
mod_version=6.0.1+1.21.1
maven_group=io.github.sythiex

midnightlib_version=1.6.7+1.21.1
phonos_version=0.3.0+1.19.2

fabric_loader_version=0.16.9
fabric_api_version=0.116.15+1.21.1

neoforge_version=21.1.248
yarn_mappings_patch_neoforge_version = 1.21+build.4

quilt_loader_version=0.19.0-beta.18
quilt_fabric_api_version=7.0.1+0.83.0-1.20
