modLoader = "javafml"
loaderVersion = "[1,)"
displayURL = "https://github.com/Sythiex/VisualOverhaul"
issueTrackerURL = "https://github.com/Sythiex/VisualOverhaul/issues"
license = "MIT"

[[mods]]
modId = "visualoverhaul"
version = "${version}"
displayName = "Visual Overhaul: Legacy"
logoFile = "icon.png"
authors = "Motschen, TeamMidnightDust, Sythiex"
description = '''
Adds better visuals for certain Minecraft Vanilla Blocks.
'''

[[mixins]]
config = "visualoverhaul.mixins.json"
[[mixins]]
config = "visualoverhaul-neoforge.mixins.json"

[[dependencies.visualoverhaul]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.visualoverhaul]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.visualoverhaul]]
modId = "midnightlib"
type = "required"
versionRange = "[1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visualoverhaul]]
modId = "amendments"
type = "optional"
ordering = "AFTER"
side = "CLIENT"
